// packages/interview-ui/src/react/VideoRecorder.tsx
import { useMemo, useRef, useState } from 'react';

type CaptureMode = 'webcam' | 'screen';

interface VideoRecorderProps {
  onRecorded: (blob: Blob) => void;
  mode?: CaptureMode;
  withAudio?: boolean;
}

export function VideoRecorder({ onRecorded, mode = 'webcam', withAudio = true }: VideoRecorderProps) {
  const recorderRef = useRef<MediaRecorder | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const chunksRef = useRef<Blob[]>([]);
  const [recording, setRecording] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const label = useMemo(() => (mode === 'screen' ? 'Screen Recorder' : 'Webcam Recorder'), [mode]);

  const start = async () => {
    setError(null);
    try {
      const stream =
        mode === 'screen'
          ? await navigator.mediaDevices.getDisplayMedia({ video: true, audio: withAudio })
          : await navigator.mediaDevices.getUserMedia({ video: true, audio: withAudio });

      streamRef.current = stream;
      chunksRef.current = [];

      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp9,opus' });
      recorderRef.current = recorder;

      recorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          chunksRef.current.push(event.data);
        }
      };

      recorder.onstop = () => {
        const blob = new Blob(chunksRef.current, { type: 'video/webm' });
        onRecorded(blob);
        streamRef.current?.getTracks().forEach((track: MediaStreamTrack) => track.stop());
      };

      recorder.start(300);
      setRecording(true);
    } catch (err) {
      setError((err as Error).message);
    }
  };

  const stop = () => {
    recorderRef.current?.stop();
    setRecording(false);
  };

  return (
    <section style={{ border: '1px solid #ddd', borderRadius: 12, padding: 12 }}>
      <h3 style={{ marginTop: 0 }}>{label}</h3>
      <div style={{ display: 'flex', gap: 8 }}>
        <button type="button" onClick={start} disabled={recording}>
          Start
        </button>
        <button type="button" onClick={stop} disabled={!recording}>
          Stop
        </button>
      </div>
      {error ? <p style={{ color: '#9f2222' }}>{error}</p> : null}
    </section>
  );
}

// packages/interview-ui/src/vue/VideoRecorder.vue
<script setup lang="ts">
import { ref } from 'vue';

const props = withDefaults(
  defineProps<{
    mode?: 'webcam' | 'screen';
    withAudio?: boolean;
  }>(),
  {
    mode: 'webcam',
    withAudio: true,
  },
);

const emit = defineEmits<{
  recorded: [blob: Blob];
}>();

const recorder = ref<MediaRecorder | null>(null);
const stream = ref<MediaStream | null>(null);
const chunks = ref<Blob[]>([]);
const recording = ref(false);
const error = ref('');

async function start() {
  error.value = '';
  try {
    stream.value =
      props.mode === 'screen'
        ? await navigator.mediaDevices.getDisplayMedia({ video: true, audio: props.withAudio })
        : await navigator.mediaDevices.getUserMedia({ video: true, audio: props.withAudio });

    recorder.value = new MediaRecorder(stream.value, { mimeType: 'video/webm;codecs=vp9,opus' });
    chunks.value = [];

    recorder.value.ondataavailable = (event: BlobEvent) => {
      if (event.data.size > 0) {
        chunks.value.push(event.data);
      }
    };

    recorder.value.onstop = () => {
      emit('recorded', new Blob(chunks.value, { type: 'video/webm' }));
      stream.value?.getTracks().forEach((track) => track.stop());
    };

    recorder.value.start(300);
    recording.value = true;
  } catch (err) {
    error.value = (err as Error).message;
  }
}

function stop() {
  recorder.value?.stop();
  recording.value = false;
}
</script>

<template>
  <section class="card">
    <h3>{{ mode === 'screen' ? 'Screen Recorder' : 'Webcam Recorder' }}</h3>
    <div class="row">
      <button :disabled="recording" @click="start">Start</button>
      <button :disabled="!recording" @click="stop">Stop</button>
    </div>
    <p v-if="error" class="error">{{ error }}</p>
  </section>
</template>

<style scoped>
.card {
  border: 1px solid #ddd;
  border-radius: 12px;
  padding: 12px;
}
.row {
  display: flex;
  gap: 8px;
}
.error {
  color: #9f2222;
}
</style>
